package applog

import (
	"github.com/stormkit-io/stormkit-io/src/lib/types"
)

// Log represents a log created by the user.
type Log struct {
	ID            types.ID `json:"logId,string,omitempty"`
	AppID         types.ID `json:"appId,string,omitempty"`
	DeploymentID  types.ID `json:"deploymentId,string,omitempty"`
	EnvironmentID types.ID `json:"envId,string,omitempty"`

	// HostName is the host name which the log was generated.
	// TODO: Drop this
	HostName string `json:"hostName"`

	// Timestamp represents the timestamp when the log was created.
	Timestamp int64 `json:"timestamp"`

	// RequestID is the request-id created by AWS lambdas.
	RequestID string `json:"requestId"`

	// Label represents the label of the log such as error,
	// info, debug, access-log or any other descriptive string.
	// It is used to group logs and easily query them.
	Label string `json:"label"`

	// Data represents the log data. It is content generated by function
	Data string `json:"data"`
}
