INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (49518,'en','AF','Africa','RW','Rwanda',false),
	 (51537,'en','AF','Africa','SO','Somalia',false),
	 (69543,'en','AS','Asia','YE','Yemen',false),
	 (99237,'en','AS','Asia','IQ','Iraq',false),
	 (102358,'en','AS','Asia','SA','Saudi Arabia',false),
	 (130758,'en','AS','Asia','IR','Iran',false),
	 (146669,'en','EU','Europe','CY','Cyprus',true),
	 (149590,'en','AF','Africa','TZ','Tanzania',false),
	 (163843,'en','AS','Asia','SY','Syria',false),
	 (174982,'en','AS','Asia','AM','Armenia',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (192950,'en','AF','Africa','KE','Kenya',false),
	 (203312,'en','AF','Africa','CD','DR Congo',false),
	 (223816,'en','AF','Africa','DJ','Djibouti',false),
	 (226074,'en','AF','Africa','UG','Uganda',false),
	 (239880,'en','AF','Africa','CF','Central African Republic',false),
	 (241170,'en','AF','Africa','SC','Seychelles',false),
	 (248816,'en','AS','Asia','JO','Jordan',false),
	 (272103,'en','AS','Asia','LB','Lebanon',false),
	 (285570,'en','AS','Asia','KW','Kuwait',false),
	 (286963,'en','AS','Asia','OM','Oman',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (289688,'en','AS','Asia','QA','Qatar',false),
	 (290291,'en','AS','Asia','BH','Bahrain',false),
	 (290557,'en','AS','Asia','AE','United Arab Emirates',false),
	 (294640,'en','AS','Asia','IL','Israel',false),
	 (298795,'en','AS','Asia','TR','Turkey',false),
	 (337996,'en','AF','Africa','ET','Ethiopia',false),
	 (338010,'en','AF','Africa','ER','Eritrea',false),
	 (357994,'en','AF','Africa','EG','Egypt',false),
	 (366755,'en','AF','Africa','SD','Sudan',false),
	 (390903,'en','EU','Europe','GR','Greece',true);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (433561,'en','AF','Africa','BI','Burundi',false),
	 (453733,'en','EU','Europe','EE','Estonia',true),
	 (458258,'en','EU','Europe','LV','Latvia',true),
	 (587116,'en','AS','Asia','AZ','Azerbaijan',false),
	 (597427,'en','EU','Europe','LT','Lithuania',true),
	 (607072,'en','EU','Europe','SJ','Svalbard and Jan Mayen',false),
	 (614540,'en','AS','Asia','GE','Georgia',false),
	 (617790,'en','EU','Europe','MD','Moldova',false),
	 (630336,'en','EU','Europe','BY','Belarus',false),
	 (660013,'en','EU','Europe','FI','Finland',true);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (661882,'en','EU','Europe','AX','Åland Islands',true),
	 (690791,'en','EU','Europe','UA','Ukraine',false),
	 (718075,'en','EU','Europe','MK','North Macedonia',false),
	 (719819,'en','EU','Europe','HU','Hungary',true),
	 (732800,'en','EU','Europe','BG','Bulgaria',true),
	 (783754,'en','EU','Europe','AL','Albania',false),
	 (798544,'en','EU','Europe','PL','Poland',true),
	 (798549,'en','EU','Europe','RO','Romania',true),
	 (831053,'en','EU','Europe','XK','Kosovo',false),
	 (878675,'en','AF','Africa','ZW','Zimbabwe',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (895949,'en','AF','Africa','ZM','Zambia',false),
	 (921929,'en','AF','Africa','KM','Comoros',false),
	 (927384,'en','AF','Africa','MW','Malawi',false),
	 (932692,'en','AF','Africa','LS','Lesotho',false),
	 (933860,'en','AF','Africa','BW','Botswana',false),
	 (934292,'en','AF','Africa','MU','Mauritius',false),
	 (934841,'en','AF','Africa','SZ','Eswatini',false),
	 (935317,'en','AF','Africa','RE','Réunion',true),
	 (953987,'en','AF','Africa','ZA','South Africa',false),
	 (1024031,'en','AF','Africa','YT','Mayotte',true);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (1036973,'en','AF','Africa','MZ','Mozambique',false),
	 (1062947,'en','AF','Africa','MG','Madagascar',false),
	 (1149361,'en','AS','Asia','AF','Afghanistan',false),
	 (1168579,'en','AS','Asia','PK','Pakistan',false),
	 (1210997,'en','AS','Asia','BD','Bangladesh',false),
	 (1218197,'en','AS','Asia','TM','Turkmenistan',false),
	 (1220409,'en','AS','Asia','TJ','Tajikistan',false),
	 (1227603,'en','AS','Asia','LK','Sri Lanka',false),
	 (1252634,'en','AS','Asia','BT','Bhutan',false),
	 (1269750,'en','AS','Asia','IN','India',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (1282028,'en','AS','Asia','MV','Maldives',false),
	 (1282588,'en','AS','Asia','IO','British Indian Ocean Territory',false),
	 (1282988,'en','AS','Asia','NP','Nepal',false),
	 (1327865,'en','AS','Asia','MM','Myanmar',false),
	 (1512440,'en','AS','Asia','UZ','Uzbekistan',false),
	 (1522867,'en','AS','Asia','KZ','Kazakhstan',false),
	 (1527747,'en','AS','Asia','KG','Kyrgyzstan',false),
	 (1546748,'en','AN','Antarctica','TF','French Southern Territories',false),
	 (1547314,'en','AN','Antarctica','HM','Heard and McDonald Islands',false),
	 (1547376,'en','AS','Asia','CC','Cocos (Keeling) Islands',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (1559582,'en','OC','Oceania','PW','Palau',false),
	 (1562822,'en','AS','Asia','VN','Vietnam',false),
	 (1605651,'en','AS','Asia','TH','Thailand',false),
	 (1643084,'en','AS','Asia','ID','Indonesia',false),
	 (1655842,'en','AS','Asia','LA','Laos',false),
	 (1668284,'en','AS','Asia','TW','Taiwan',false),
	 (1694008,'en','AS','Asia','PH','Philippines',false),
	 (1733045,'en','AS','Asia','MY','Malaysia',false),
	 (1814991,'en','AS','Asia','CN','China',false),
	 (1819730,'en','AS','Asia','HK','Hong Kong',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (1820814,'en','AS','Asia','BN','Brunei',false),
	 (1821275,'en','AS','Asia','MO','Macao',false),
	 (1831722,'en','AS','Asia','KH','Cambodia',false),
	 (1835841,'en','AS','Asia','KR','South Korea',false),
	 (1861060,'en','AS','Asia','JP','Japan',false),
	 (1873107,'en','AS','Asia','KP','North Korea',false),
	 (1880251,'en','AS','Asia','SG','Singapore',false),
	 (1899402,'en','OC','Oceania','CK','Cook Islands',false),
	 (1966436,'en','OC','Oceania','TL','Timor-Leste',false),
	 (2017370,'en','EU','Europe','RU','Russia',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (2029969,'en','AS','Asia','MN','Mongolia',false),
	 (2077456,'en','OC','Oceania','AU','Australia',false),
	 (2078138,'en','OC','Oceania','CX','Christmas Island',false),
	 (2080185,'en','OC','Oceania','MH','Marshall Islands',false),
	 (2081918,'en','OC','Oceania','FM','Federated States of Micronesia',false),
	 (2088628,'en','OC','Oceania','PG','Papua New Guinea',false),
	 (2103350,'en','OC','Oceania','SB','Solomon Islands',false),
	 (2110297,'en','OC','Oceania','TV','Tuvalu',false),
	 (2110425,'en','OC','Oceania','NR','Nauru',false),
	 (2134431,'en','OC','Oceania','VU','Vanuatu',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (2139685,'en','OC','Oceania','NC','New Caledonia',false),
	 (2155115,'en','OC','Oceania','NF','Norfolk Island',false),
	 (2186224,'en','OC','Oceania','NZ','New Zealand',false),
	 (2205218,'en','OC','Oceania','FJ','Fiji',false),
	 (2215636,'en','AF','Africa','LY','Libya',false),
	 (2233387,'en','AF','Africa','CM','Cameroon',false),
	 (2245662,'en','AF','Africa','SN','Senegal',false),
	 (2260494,'en','AF','Africa','CG','Congo Republic',false),
	 (2264397,'en','EU','Europe','PT','Portugal',true),
	 (2275384,'en','AF','Africa','LR','Liberia',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (2287781,'en','AF','Africa','CI','Ivory Coast',false),
	 (2300660,'en','AF','Africa','GH','Ghana',false),
	 (2309096,'en','AF','Africa','GQ','Equatorial Guinea',false),
	 (2328926,'en','AF','Africa','NG','Nigeria',false),
	 (2361809,'en','AF','Africa','BF','Burkina Faso',false),
	 (2363686,'en','AF','Africa','TG','Togo',false),
	 (2372248,'en','AF','Africa','GW','Guinea-Bissau',false),
	 (2378080,'en','AF','Africa','MR','Mauritania',false),
	 (2395170,'en','AF','Africa','BJ','Benin',false),
	 (2400553,'en','AF','Africa','GA','Gabon',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (2403846,'en','AF','Africa','SL','Sierra Leone',false),
	 (2410758,'en','AF','Africa','ST','São Tomé and Príncipe',false),
	 (2411586,'en','EU','Europe','GI','Gibraltar',false),
	 (2413451,'en','AF','Africa','GM','Gambia',false),
	 (2420477,'en','AF','Africa','GN','Guinea',false),
	 (2434508,'en','AF','Africa','TD','Chad',false),
	 (2440476,'en','AF','Africa','NE','Niger',false),
	 (2453866,'en','AF','Africa','ML','Mali',false),
	 (2461445,'en','AF','Africa','EH','Western Sahara',false),
	 (2464461,'en','AF','Africa','TN','Tunisia',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (2510769,'en','EU','Europe','ES','Spain',true),
	 (2542007,'en','AF','Africa','MA','Morocco',false),
	 (2562770,'en','EU','Europe','MT','Malta',true),
	 (2589581,'en','AF','Africa','DZ','Algeria',false),
	 (2622320,'en','EU','Europe','FO','Faroe Islands',false),
	 (2623032,'en','EU','Europe','DK','Denmark',true),
	 (2629691,'en','EU','Europe','IS','Iceland',false),
	 (2635167,'en','EU','Europe','GB','United Kingdom',false),
	 (2658434,'en','EU','Europe','CH','Switzerland',false),
	 (2661886,'en','EU','Europe','SE','Sweden',true);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (2750405,'en','EU','Europe','NL','The Netherlands',true),
	 (2782113,'en','EU','Europe','AT','Austria',true),
	 (2802361,'en','EU','Europe','BE','Belgium',true),
	 (2921044,'en','EU','Europe','DE','Germany',true),
	 (2960313,'en','EU','Europe','LU','Luxembourg',true),
	 (2963597,'en','EU','Europe','IE','Ireland',true),
	 (2993457,'en','EU','Europe','MC','Monaco',false),
	 (3017382,'en','EU','Europe','FR','France',true),
	 (3041565,'en','EU','Europe','AD','Andorra',false),
	 (3042058,'en','EU','Europe','LI','Liechtenstein',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (3042142,'en','EU','Europe','JE','Jersey',false),
	 (3042225,'en','EU','Europe','IM','Isle of Man',false),
	 (3042362,'en','EU','Europe','GG','Guernsey',false),
	 (3057568,'en','EU','Europe','SK','Slovakia',true),
	 (3077311,'en','EU','Europe','CZ','Czechia',true),
	 (3144096,'en','EU','Europe','NO','Norway',false),
	 (3164670,'en','EU','Europe','VA','Vatican City',false),
	 (3168068,'en','EU','Europe','SM','San Marino',false),
	 (3175395,'en','EU','Europe','IT','Italy',true),
	 (3190538,'en','EU','Europe','SI','Slovenia',true);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (3194884,'en','EU','Europe','ME','Montenegro',false),
	 (3202326,'en','EU','Europe','HR','Croatia',true),
	 (3277605,'en','EU','Europe','BA','Bosnia and Herzegovina',false),
	 (3351879,'en','AF','Africa','AO','Angola',false),
	 (3355338,'en','AF','Africa','NA','Namibia',false),
	 (3370751,'en','AF','Africa','SH','Saint Helena',false),
	 (3371123,'en','AN','Antarctica','BV','Bouvet Island',false),
	 (3374084,'en','NA','North America','BB','Barbados',false),
	 (3374766,'en','AF','Africa','CV','Cabo Verde',false),
	 (3378535,'en','SA','South America','GY','Guyana',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (3381670,'en','SA','South America','GF','French Guiana',true),
	 (3382998,'en','SA','South America','SR','Suriname',false),
	 (3424932,'en','NA','North America','PM','Saint Pierre and Miquelon',false),
	 (3425505,'en','NA','North America','GL','Greenland',false),
	 (3437598,'en','SA','South America','PY','Paraguay',false),
	 (3439705,'en','SA','South America','UY','Uruguay',false),
	 (3469034,'en','SA','South America','BR','Brazil',false),
	 (3474414,'en','SA','South America','FK','Falkland Islands',false),
	 (3474415,'en','AN','Antarctica','GS','South Georgia and the South Sandwich Islands',false),
	 (3489940,'en','NA','North America','JM','Jamaica',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (3508796,'en','NA','North America','DO','Dominican Republic',false),
	 (3562981,'en','NA','North America','CU','Cuba',false),
	 (3570311,'en','NA','North America','MQ','Martinique',true),
	 (3572887,'en','NA','North America','BS','Bahamas',false),
	 (3573345,'en','NA','North America','BM','Bermuda',false),
	 (3573511,'en','NA','North America','AI','Anguilla',false),
	 (3573591,'en','NA','North America','TT','Trinidad and Tobago',false),
	 (3575174,'en','NA','North America','KN','St Kitts and Nevis',false),
	 (3575830,'en','NA','North America','DM','Dominica',false),
	 (3576396,'en','NA','North America','AG','Antigua and Barbuda',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (3576468,'en','NA','North America','LC','Saint Lucia',false),
	 (3576916,'en','NA','North America','TC','Turks and Caicos Islands',false),
	 (3577279,'en','NA','North America','AW','Aruba',false),
	 (3577718,'en','NA','North America','VG','British Virgin Islands',false),
	 (3577815,'en','NA','North America','VC','St Vincent and Grenadines',false),
	 (3578097,'en','NA','North America','MS','Montserrat',false),
	 (3578421,'en','NA','North America','MF','Saint Martin',true),
	 (3578476,'en','NA','North America','BL','Saint Barthélemy',false),
	 (3579143,'en','NA','North America','GP','Guadeloupe',true),
	 (3580239,'en','NA','North America','GD','Grenada',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (3580718,'en','NA','North America','KY','Cayman Islands',false),
	 (3582678,'en','NA','North America','BZ','Belize',false),
	 (3585968,'en','NA','North America','SV','El Salvador',false),
	 (3595528,'en','NA','North America','GT','Guatemala',false),
	 (3608932,'en','NA','North America','HN','Honduras',false),
	 (3617476,'en','NA','North America','NI','Nicaragua',false),
	 (3624060,'en','NA','North America','CR','Costa Rica',false),
	 (3625428,'en','SA','South America','VE','Venezuela',false),
	 (3658394,'en','SA','South America','EC','Ecuador',false),
	 (3686110,'en','SA','South America','CO','Colombia',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (3703430,'en','NA','North America','PA','Panama',false),
	 (3723988,'en','NA','North America','HT','Haiti',false),
	 (3865483,'en','SA','South America','AR','Argentina',false),
	 (3895114,'en','SA','South America','CL','Chile',false),
	 (3923057,'en','SA','South America','BO','Bolivia',false),
	 (3932488,'en','SA','South America','PE','Peru',false),
	 (3996063,'en','NA','North America','MX','Mexico',false),
	 (4030656,'en','OC','Oceania','PF','French Polynesia',false),
	 (4030699,'en','OC','Oceania','PN','Pitcairn Islands',false),
	 (4030945,'en','OC','Oceania','KI','Kiribati',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (4031074,'en','OC','Oceania','TK','Tokelau',false),
	 (4032283,'en','OC','Oceania','TO','Tonga',false),
	 (4034749,'en','OC','Oceania','WF','Wallis and Futuna',false),
	 (4034894,'en','OC','Oceania','WS','Samoa',false),
	 (4036232,'en','OC','Oceania','NU','Niue',false),
	 (4041468,'en','OC','Oceania','MP','Northern Mariana Islands',false),
	 (4043988,'en','OC','Oceania','GU','Guam',false),
	 (4566966,'en','NA','North America','PR','Puerto Rico',false),
	 (4796775,'en','NA','North America','VI','U.S. Virgin Islands',false),
	 (5854968,'en','OC','Oceania','UM','U.S. Outlying Islands',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (5880801,'en','OC','Oceania','AS','American Samoa',false),
	 (6251999,'en','NA','North America','CA','Canada',false),
	 (6252001,'en','NA','North America','US','United States',false),
	 (6254930,'en','AS','Asia','PS','Palestine',false),
	 (6255147,'en','AS','Asia',NULL,NULL,false),
	 (6255148,'en','EU','Europe',NULL,NULL,false),
	 (6290252,'en','EU','Europe','RS','Serbia',false),
	 (6697173,'en','AN','Antarctica','AQ','Antarctica',false),
	 (7609695,'en','NA','North America','SX','Sint Maarten',false),
	 (7626836,'en','NA','North America','CW','Curaçao',false);
INSERT INTO skitapi.geo_countries (geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,is_in_european_union) VALUES
	 (7626844,'en','NA','North America','BQ','Bonaire, Sint Eustatius, and Saba',false),
	 (7909807,'en','AF','Africa','SS','South Sudan',false);
