// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	client "github.com/alibabacloud-go/fc-20230330/v4/client"

	mock "github.com/stretchr/testify/mock"
)

// AlibabaSDK is an autogenerated mock type for the AlibabaSDK type
type AlibabaSDK struct {
	mock.Mock
}

// CreateFunction provides a mock function with given fields: _a0
func (_m *AlibabaSDK) CreateFunction(_a0 *client.CreateFunctionRequest) (*client.CreateFunctionResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateFunction")
	}

	var r0 *client.CreateFunctionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*client.CreateFunctionRequest) (*client.CreateFunctionResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*client.CreateFunctionRequest) *client.CreateFunctionResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.CreateFunctionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*client.CreateFunctionRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteFunctionVersion provides a mock function with given fields: _a0, _a1
func (_m *AlibabaSDK) DeleteFunctionVersion(_a0 *string, _a1 *string) (*client.DeleteFunctionVersionResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFunctionVersion")
	}

	var r0 *client.DeleteFunctionVersionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*string, *string) (*client.DeleteFunctionVersionResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*string, *string) *client.DeleteFunctionVersionResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.DeleteFunctionVersionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*string, *string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFunction provides a mock function with given fields: _a0, _a1
func (_m *AlibabaSDK) GetFunction(_a0 *string, _a1 *client.GetFunctionRequest) (*client.GetFunctionResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetFunction")
	}

	var r0 *client.GetFunctionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*string, *client.GetFunctionRequest) (*client.GetFunctionResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*string, *client.GetFunctionRequest) *client.GetFunctionResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetFunctionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*string, *client.GetFunctionRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvokeFunction provides a mock function with given fields: _a0, _a1
func (_m *AlibabaSDK) InvokeFunction(_a0 *string, _a1 *client.InvokeFunctionRequest) (*client.InvokeFunctionResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InvokeFunction")
	}

	var r0 *client.InvokeFunctionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*string, *client.InvokeFunctionRequest) (*client.InvokeFunctionResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*string, *client.InvokeFunctionRequest) *client.InvokeFunctionResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.InvokeFunctionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*string, *client.InvokeFunctionRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PublishFunctionVersion provides a mock function with given fields: _a0, _a1
func (_m *AlibabaSDK) PublishFunctionVersion(_a0 *string, _a1 *client.PublishFunctionVersionRequest) (*client.PublishFunctionVersionResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PublishFunctionVersion")
	}

	var r0 *client.PublishFunctionVersionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*string, *client.PublishFunctionVersionRequest) (*client.PublishFunctionVersionResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*string, *client.PublishFunctionVersionRequest) *client.PublishFunctionVersionResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PublishFunctionVersionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*string, *client.PublishFunctionVersionRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateFunction provides a mock function with given fields: _a0, _a1
func (_m *AlibabaSDK) UpdateFunction(_a0 *string, _a1 *client.UpdateFunctionRequest) (*client.UpdateFunctionResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFunction")
	}

	var r0 *client.UpdateFunctionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*string, *client.UpdateFunctionRequest) (*client.UpdateFunctionResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*string, *client.UpdateFunctionRequest) *client.UpdateFunctionResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.UpdateFunctionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*string, *client.UpdateFunctionRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAlibabaSDK creates a new instance of AlibabaSDK. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlibabaSDK(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlibabaSDK {
	mock := &AlibabaSDK{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
