// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	audit "github.com/stormkit-io/stormkit-io/src/ee/api/audit"
	mock "github.com/stretchr/testify/mock"
)

// AuditContext is an autogenerated mock type for the AuditContext type
type AuditContext struct {
	mock.Mock
}

// GetAuditData provides a mock function with no fields
func (_m *AuditContext) GetAuditData() audit.AuditData {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAuditData")
	}

	var r0 audit.AuditData
	if rf, ok := ret.Get(0).(func() audit.AuditData); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(audit.AuditData)
	}

	return r0
}

// NewAuditContext creates a new instance of AuditContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditContext {
	mock := &AuditContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
