// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	runner "github.com/stormkit-io/stormkit-io/src/ce/runner"
	mock "github.com/stretchr/testify/mock"
)

// BundlerInterface is an autogenerated mock type for the BundlerInterface type
type BundlerInterface struct {
	mock.Mock
}

// Bundle provides a mock function with given fields: _a0
func (_m *BundlerInterface) Bundle(_a0 context.Context) (*runner.Artifacts, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Bundle")
	}

	var r0 *runner.Artifacts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*runner.Artifacts, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *runner.Artifacts); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runner.Artifacts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseHeaders provides a mock function with given fields: _a0
func (_m *BundlerInterface) ParseHeaders(_a0 *runner.Artifacts) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ParseHeaders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*runner.Artifacts) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ParseRedirects provides a mock function with given fields: _a0
func (_m *BundlerInterface) ParseRedirects(_a0 *runner.Artifacts) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ParseRedirects")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*runner.Artifacts) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Zip provides a mock function with given fields: _a0
func (_m *BundlerInterface) Zip(_a0 *runner.Artifacts) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Zip")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*runner.Artifacts) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBundlerInterface creates a new instance of BundlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBundlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BundlerInterface {
	mock := &BundlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
