// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	types "github.com/stormkit-io/stormkit-io/src/lib/types"
	mock "github.com/stretchr/testify/mock"
)

// CacheInterface is an autogenerated mock type for the CacheInterface type
type CacheInterface struct {
	mock.Mock
}

// Reset provides a mock function with given fields: envID, keys
func (_m *CacheInterface) Reset(envID types.ID, keys ...string) error {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, envID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.ID, ...string) error); ok {
		r0 = rf(envID, keys...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCacheInterface creates a new instance of CacheInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheInterface {
	mock := &CacheInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
