// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	integrations "github.com/stormkit-io/stormkit-io/src/lib/integrations"
	mock "github.com/stretchr/testify/mock"
)

// ClientInterface is an autogenerated mock type for the ClientInterface type
type ClientInterface struct {
	mock.Mock
}

// DeleteArtifacts provides a mock function with given fields: _a0, _a1
func (_m *ClientInterface) DeleteArtifacts(_a0 context.Context, _a1 integrations.DeleteArtifactsArgs) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArtifacts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, integrations.DeleteArtifactsArgs) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFile provides a mock function with given fields: _a0
func (_m *ClientInterface) GetFile(_a0 integrations.GetFileArgs) (*integrations.GetFileResult, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 *integrations.GetFileResult
	var r1 error
	if rf, ok := ret.Get(0).(func(integrations.GetFileArgs) (*integrations.GetFileResult, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(integrations.GetFileArgs) *integrations.GetFileResult); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*integrations.GetFileResult)
		}
	}

	if rf, ok := ret.Get(1).(func(integrations.GetFileArgs) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Invoke provides a mock function with given fields: _a0
func (_m *ClientInterface) Invoke(_a0 integrations.InvokeArgs) (*integrations.InvokeResult, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 *integrations.InvokeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(integrations.InvokeArgs) (*integrations.InvokeResult, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(integrations.InvokeArgs) *integrations.InvokeResult); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*integrations.InvokeResult)
		}
	}

	if rf, ok := ret.Get(1).(func(integrations.InvokeArgs) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Name provides a mock function with no fields
func (_m *ClientInterface) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Upload provides a mock function with given fields: _a0
func (_m *ClientInterface) Upload(_a0 integrations.UploadArgs) (*integrations.UploadResult, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *integrations.UploadResult
	var r1 error
	if rf, ok := ret.Get(0).(func(integrations.UploadArgs) (*integrations.UploadResult, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(integrations.UploadArgs) *integrations.UploadResult); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*integrations.UploadResult)
		}
	}

	if rf, ok := ret.Get(1).(func(integrations.UploadArgs) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientInterface creates a new instance of ClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientInterface {
	mock := &ClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
