// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	oauth2 "golang.org/x/oauth2"

	shttp "github.com/stormkit-io/stormkit-io/src/lib/shttp"

	skauth "github.com/stormkit-io/stormkit-io/src/ce/api/app/skauth"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// AuthCodeURL provides a mock function with given fields: data
func (_m *Client) AuthCodeURL(data skauth.AuthCodeURLParams) (string, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for AuthCodeURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(skauth.AuthCodeURLParams) (string, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func(skauth.AuthCodeURLParams) string); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(skauth.AuthCodeURLParams) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Exchange provides a mock function with given fields: ctx, req
func (_m *Client) Exchange(ctx context.Context, req *shttp.RequestContext) (*oauth2.Token, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *oauth2.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *shttp.RequestContext) (*oauth2.Token, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *shttp.RequestContext) *oauth2.Token); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *shttp.RequestContext) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserInfo provides a mock function with given fields: ctx, token
func (_m *Client) UserInfo(ctx context.Context, token *oauth2.Token) (*skauth.UserInfo, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for UserInfo")
	}

	var r0 *skauth.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *oauth2.Token) (*skauth.UserInfo, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *oauth2.Token) *skauth.UserInfo); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*skauth.UserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *oauth2.Token) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
