// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	exec "os/exec"

	sys "github.com/stormkit-io/stormkit-io/src/lib/utils/sys"
	mock "github.com/stretchr/testify/mock"
)

// CommandInterface is an autogenerated mock type for the CommandInterface type
type CommandInterface struct {
	mock.Mock
}

// Cmd provides a mock function with no fields
func (_m *CommandInterface) Cmd() *exec.Cmd {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cmd")
	}

	var r0 *exec.Cmd
	if rf, ok := ret.Get(0).(func() *exec.Cmd); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}

	return r0
}

// CombinedOutput provides a mock function with no fields
func (_m *CommandInterface) CombinedOutput() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CombinedOutput")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Output provides a mock function with no fields
func (_m *CommandInterface) Output() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Output")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Run provides a mock function with no fields
func (_m *CommandInterface) Run() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetOpts provides a mock function with given fields: opts
func (_m *CommandInterface) SetOpts(opts sys.CommandOpts) sys.CommandInterface {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for SetOpts")
	}

	var r0 sys.CommandInterface
	if rf, ok := ret.Get(0).(func(sys.CommandOpts) sys.CommandInterface); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sys.CommandInterface)
		}
	}

	return r0
}

// Start provides a mock function with no fields
func (_m *CommandInterface) Start() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// String provides a mock function with no fields
func (_m *CommandInterface) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Wait provides a mock function with no fields
func (_m *CommandInterface) Wait() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommandInterface creates a new instance of CommandInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandInterface {
	mock := &CommandInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
