// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	deployservice "github.com/stormkit-io/stormkit-io/src/ce/api/app/deployservice"
	mock "github.com/stretchr/testify/mock"
)

// DeployerService is an autogenerated mock type for the DeployerService type
type DeployerService struct {
	mock.Mock
}

// SendPayload provides a mock function with given fields: args
func (_m *DeployerService) SendPayload(args deployservice.SendPayloadArgs) error {
	ret := _m.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for SendPayload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(deployservice.SendPayloadArgs) error); ok {
		r0 = rf(args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StopDeployment provides a mock function with given fields: runID
func (_m *DeployerService) StopDeployment(runID int64) error {
	ret := _m.Called(runID)

	if len(ret) == 0 {
		panic("no return value specified for StopDeployment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(runID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeployerService creates a new instance of DeployerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeployerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeployerService {
	mock := &DeployerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
