// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	app "github.com/stormkit-io/stormkit-io/src/ce/api/app"

	deploy "github.com/stormkit-io/stormkit-io/src/ce/api/app/deploy"

	mock "github.com/stretchr/testify/mock"
)

// Deployer is an autogenerated mock type for the Deployer type
type Deployer struct {
	mock.Mock
}

// Deploy provides a mock function with given fields: _a0, _a1, _a2
func (_m *Deployer) Deploy(_a0 context.Context, _a1 *app.App, _a2 *deploy.Deployment) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Deploy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *app.App, *deploy.Deployment) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeployer creates a new instance of Deployer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeployer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Deployer {
	mock := &Deployer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
