// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DownloadFunc is an autogenerated mock type for the DownloadFunc type
type DownloadFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: deploymentID, bucketname, keyprefix
func (_m *DownloadFunc) Execute(deploymentID string, bucketname string, keyprefix string) (string, error) {
	ret := _m.Called(deploymentID, bucketname, keyprefix)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return rf(deploymentID, bucketname, keyprefix)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(deploymentID, bucketname, keyprefix)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(deploymentID, bucketname, keyprefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDownloadFunc creates a new instance of DownloadFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDownloadFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *DownloadFunc {
	mock := &DownloadFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
