// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Flusher is an autogenerated mock type for the Flusher type
type Flusher struct {
	mock.Mock
}

// Write provides a mock function with given fields: items
func (_m *Flusher) Write(items []interface{}) {
	_m.Called(items)
}

// NewFlusher creates a new instance of Flusher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlusher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Flusher {
	mock := &Flusher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
