// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FlusherFunc is an autogenerated mock type for the FlusherFunc type
type FlusherFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: items
func (_m *FlusherFunc) Execute(items []interface{}) {
	_m.Called(items)
}

// NewFlusherFunc creates a new instance of FlusherFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlusherFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlusherFunc {
	mock := &FlusherFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
