// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	github "github.com/google/go-github/v71/github"
	mock "github.com/stretchr/testify/mock"

	oauth "github.com/stormkit-io/stormkit-io/src/ce/api/oauth"
)

// GithubClient is an autogenerated mock type for the GithubClient type
type GithubClient struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: _a0, _a1
func (_m *GithubClient) GetUser(_a0 context.Context, _a1 string) (*github.User, *github.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *github.User
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*github.User, *github.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *github.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *github.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListEmails provides a mock function with no fields
func (_m *GithubClient) ListEmails() ([]oauth.Email, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListEmails")
	}

	var r0 []oauth.Email
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]oauth.Email, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []oauth.Email); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]oauth.Email)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRepos provides a mock function with given fields: _a0, _a1
func (_m *GithubClient) ListRepos(_a0 context.Context, _a1 *github.ListOptions) (*github.ListRepositories, *github.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListRepos")
	}

	var r0 *github.ListRepositories
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *github.ListOptions) (*github.ListRepositories, *github.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *github.ListOptions) *github.ListRepositories); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.ListRepositories)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *github.ListOptions) *github.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *github.ListOptions) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListUserInstallations provides a mock function with given fields: _a0, _a1
func (_m *GithubClient) ListUserInstallations(_a0 context.Context, _a1 *github.ListOptions) ([]*github.Installation, *github.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListUserInstallations")
	}

	var r0 []*github.Installation
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *github.ListOptions) ([]*github.Installation, *github.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *github.ListOptions) []*github.Installation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Installation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *github.ListOptions) *github.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *github.ListOptions) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserProfile provides a mock function with no fields
func (_m *GithubClient) UserProfile() (*oauth.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserProfile")
	}

	var r0 *oauth.User
	var r1 error
	if rf, ok := ret.Get(0).(func() (*oauth.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *oauth.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGithubClient creates a new instance of GithubClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGithubClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GithubClient {
	mock := &GithubClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
