// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	shttp "github.com/stormkit-io/stormkit-io/src/lib/shttp"
	mock "github.com/stretchr/testify/mock"
)

// HandlerFunc is an autogenerated mock type for the HandlerFunc type
type HandlerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: method, path, fn
func (_m *HandlerFunc) Execute(method string, path string, fn shttp.RequestFunc) *shttp.Response {
	ret := _m.Called(method, path, fn)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *shttp.Response
	if rf, ok := ret.Get(0).(func(string, string, shttp.RequestFunc) *shttp.Response); ok {
		r0 = rf(method, path, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shttp.Response)
		}
	}

	return r0
}

// NewHandlerFunc creates a new instance of HandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandlerFunc {
	mock := &HandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
