// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	integrations "github.com/stormkit-io/stormkit-io/src/lib/integrations"
	mock "github.com/stretchr/testify/mock"
)

// HetznerInterface is an autogenerated mock type for the HetznerInterface type
type HetznerInterface struct {
	mock.Mock
}

// CreateServer provides a mock function with given fields: ctx, opts
func (_m *HetznerInterface) CreateServer(ctx context.Context, opts integrations.CreateServerOpts) (*integrations.ServerOutput, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateServer")
	}

	var r0 *integrations.ServerOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, integrations.CreateServerOpts) (*integrations.ServerOutput, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, integrations.CreateServerOpts) *integrations.ServerOutput); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*integrations.ServerOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, integrations.CreateServerOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHetznerInterface creates a new instance of HetznerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHetznerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HetznerInterface {
	mock := &HetznerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
