// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ImageOptimizer is an autogenerated mock type for the ImageOptimizer type
type ImageOptimizer struct {
	mock.Mock
}

// Optimize provides a mock function with given fields: content, width, height, smart
func (_m *ImageOptimizer) Optimize(content []byte, width int, height int, smart bool) ([]byte, error) {
	ret := _m.Called(content, width, height, smart)

	if len(ret) == 0 {
		panic("no return value specified for Optimize")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, int, int, bool) ([]byte, error)); ok {
		return rf(content, width, height, smart)
	}
	if rf, ok := ret.Get(0).(func([]byte, int, int, bool) []byte); ok {
		r0 = rf(content, width, height, smart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, int, int, bool) error); ok {
		r1 = rf(content, width, height, smart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewImageOptimizer creates a new instance of ImageOptimizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageOptimizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageOptimizer {
	mock := &ImageOptimizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
