// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	rediscache "github.com/stormkit-io/stormkit-io/src/lib/rediscache"
	mock "github.com/stretchr/testify/mock"
)

// MicroServiceInterface is an autogenerated mock type for the MicroServiceInterface type
type MicroServiceInterface struct {
	mock.Mock
}

// Broadcast provides a mock function with given fields: _a0, _a1
func (_m *MicroServiceInterface) Broadcast(_a0 string, _a1 ...string) error {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Broadcast")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...string) error); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DelAll provides a mock function with given fields: _a0, _a1
func (_m *MicroServiceInterface) DelAll(_a0 string, _a1 []string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DelAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: _a0, _a1
func (_m *MicroServiceInterface) GetAll(_a0 string, _a1 []string) (map[string]string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string) (map[string]string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, []string) map[string]string); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Key provides a mock function with given fields: _a0
func (_m *MicroServiceInterface) Key(_a0 string) string {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Key")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// List provides a mock function with given fields: _a0
func (_m *MicroServiceInterface) List(_a0 []string) ([]*rediscache.MicroService, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*rediscache.MicroService
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) ([]*rediscache.MicroService, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]string) []*rediscache.MicroService); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*rediscache.MicroService)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceID provides a mock function with no fields
func (_m *MicroServiceInterface) ServiceID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetAll provides a mock function with given fields: _a0, _a1, _a2
func (_m *MicroServiceInterface) SetAll(_a0 string, _a1 string, _a2 []string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SetAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: _a0, _a1
func (_m *MicroServiceInterface) Subscribe(_a0 string, _a1 rediscache.Handler) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, rediscache.Handler) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscribeAsync provides a mock function with given fields: _a0, _a1
func (_m *MicroServiceInterface) SubscribeAsync(_a0 string, _a1 rediscache.Handler) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeAsync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, rediscache.Handler) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMicroServiceInterface creates a new instance of MicroServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMicroServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MicroServiceInterface {
	mock := &MicroServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
