// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mise "github.com/stormkit-io/stormkit-io/src/lib/utils/mise"
	mock "github.com/stretchr/testify/mock"
)

// MiseInterface is an autogenerated mock type for the MiseInterface type
type MiseInterface struct {
	mock.Mock
}

// BinPaths provides a mock function with given fields: _a0
func (_m *MiseInterface) BinPaths(_a0 context.Context) (map[string]string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for BinPaths")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InstallGlobal provides a mock function with given fields: _a0, _a1
func (_m *MiseInterface) InstallGlobal(_a0 context.Context, _a1 string) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InstallGlobal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InstallLocal provides a mock function with given fields: _a0, _a1
func (_m *MiseInterface) InstallLocal(_a0 context.Context, _a1 mise.LocalOpts) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InstallLocal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, mise.LocalOpts) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InstallMise provides a mock function with given fields: _a0
func (_m *MiseInterface) InstallMise(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for InstallMise")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListGlobal provides a mock function with given fields: _a0
func (_m *MiseInterface) ListGlobal(_a0 context.Context) (map[string][]mise.ListOutput, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListGlobal")
	}

	var r0 map[string][]mise.ListOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string][]mise.ListOutput, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string][]mise.ListOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]mise.ListOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListLocal provides a mock function with given fields: _a0, _a1
func (_m *MiseInterface) ListLocal(_a0 context.Context, _a1 mise.LocalOpts) ([]string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListLocal")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, mise.LocalOpts) ([]string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, mise.LocalOpts) []string); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, mise.LocalOpts) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Prune provides a mock function with given fields: ctx, exceptRuntimes
func (_m *MiseInterface) Prune(ctx context.Context, exceptRuntimes []string) error {
	ret := _m.Called(ctx, exceptRuntimes)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, exceptRuntimes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelfUpdate provides a mock function with given fields: ctx
func (_m *MiseInterface) SelfUpdate(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SelfUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Version provides a mock function with no fields
func (_m *MiseInterface) Version() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMiseInterface creates a new instance of MiseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMiseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MiseInterface {
	mock := &MiseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
