// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	databasetest "github.com/stormkit-io/stormkit-io/src/lib/database/databasetest"

	mock "github.com/stretchr/testify/mock"
)

// MockObject is an autogenerated mock type for the MockObject type
type MockObject struct {
	mock.Mock
}

// Insert provides a mock function with given fields: conn
func (_m *MockObject) Insert(conn databasetest.TestDB) error {
	ret := _m.Called(conn)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(databasetest.TestDB) error); ok {
		r0 = rf(conn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockObject creates a new instance of MockObject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObject(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObject {
	mock := &MockObject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
