// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	shttperr "github.com/stormkit-io/stormkit-io/src/lib/shttp/shttperr"
)

// Model is an autogenerated mock type for the Model type
type Model struct {
	mock.Mock
}

// Validate provides a mock function with no fields
func (_m *Model) Validate() *shttperr.ValidationError {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *shttperr.ValidationError
	if rf, ok := ret.Get(0).(func() *shttperr.ValidationError); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shttperr.ValidationError)
		}
	}

	return r0
}

// NewModel creates a new instance of Model. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *Model {
	mock := &Model{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
