// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	github "github.com/google/go-github/v71/github"

	mock "github.com/stretchr/testify/mock"
)

// ReleaseClient is an autogenerated mock type for the ReleaseClient type
type ReleaseClient struct {
	mock.Mock
}

// GetBranch provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *ReleaseClient) GetBranch(_a0 context.Context, _a1 string, _a2 string, _a3 string, _a4 int) (*github.Branch, *github.Response, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for GetBranch")
	}

	var r0 *github.Branch
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int) (*github.Branch, *github.Response, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int) *github.Branch); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int) *github.Response); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, int) error); ok {
		r2 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetLatestRelease provides a mock function with given fields: _a0, _a1, _a2
func (_m *ReleaseClient) GetLatestRelease(_a0 context.Context, _a1 string, _a2 string) (*github.RepositoryRelease, *github.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestRelease")
	}

	var r0 *github.RepositoryRelease
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*github.RepositoryRelease, *github.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *github.RepositoryRelease); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.RepositoryRelease)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *github.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewReleaseClient creates a new instance of ReleaseClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReleaseClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReleaseClient {
	mock := &ReleaseClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
