// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RepoInterface is an autogenerated mock type for the RepoInterface type
type RepoInterface struct {
	mock.Mock
}

// Address provides a mock function with no fields
func (_m *RepoInterface) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Checkout provides a mock function with given fields: _a0
func (_m *RepoInterface) Checkout(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CommitInfo provides a mock function with no fields
func (_m *RepoInterface) CommitInfo() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CommitInfo")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// IsBitbucket provides a mock function with no fields
func (_m *RepoInterface) IsBitbucket() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsBitbucket")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsGithub provides a mock function with no fields
func (_m *RepoInterface) IsGithub() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsGithub")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsGitlab provides a mock function with no fields
func (_m *RepoInterface) IsGitlab() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsGitlab")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewRepoInterface creates a new instance of RepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepoInterface {
	mock := &RepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
