// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	shttp "github.com/stormkit-io/stormkit-io/src/lib/shttp"
	mock "github.com/stretchr/testify/mock"
)

// RequestFunc is an autogenerated mock type for the RequestFunc type
type RequestFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *RequestFunc) Execute(_a0 *shttp.RequestContext) *shttp.Response {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *shttp.Response
	if rf, ok := ret.Get(0).(func(*shttp.RequestContext) *shttp.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shttp.Response)
		}
	}

	return r0
}

// NewRequestFunc creates a new instance of RequestFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestFunc {
	mock := &RequestFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
