// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	io "io"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	shttp "github.com/stormkit-io/stormkit-io/src/lib/shttp"

	time "time"
)

// RequestInterface is an autogenerated mock type for the RequestInterface type
type RequestInterface struct {
	mock.Mock
}

// Do provides a mock function with no fields
func (_m *RequestInterface) Do() (*shttp.HTTPResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *shttp.HTTPResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*shttp.HTTPResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *shttp.HTTPResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shttp.HTTPResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FollowRedirects provides a mock function with given fields: _a0
func (_m *RequestInterface) FollowRedirects(_a0 bool) shttp.RequestInterface {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for FollowRedirects")
	}

	var r0 shttp.RequestInterface
	if rf, ok := ret.Get(0).(func(bool) shttp.RequestInterface); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shttp.RequestInterface)
		}
	}

	return r0
}

// Headers provides a mock function with given fields: headers
func (_m *RequestInterface) Headers(headers http.Header) shttp.RequestInterface {
	ret := _m.Called(headers)

	if len(ret) == 0 {
		panic("no return value specified for Headers")
	}

	var r0 shttp.RequestInterface
	if rf, ok := ret.Get(0).(func(http.Header) shttp.RequestInterface); ok {
		r0 = rf(headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shttp.RequestInterface)
		}
	}

	return r0
}

// Method provides a mock function with given fields: method
func (_m *RequestInterface) Method(method string) shttp.RequestInterface {
	ret := _m.Called(method)

	if len(ret) == 0 {
		panic("no return value specified for Method")
	}

	var r0 shttp.RequestInterface
	if rf, ok := ret.Get(0).(func(string) shttp.RequestInterface); ok {
		r0 = rf(method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shttp.RequestInterface)
		}
	}

	return r0
}

// Payload provides a mock function with given fields: payload
func (_m *RequestInterface) Payload(payload interface{}) shttp.RequestInterface {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for Payload")
	}

	var r0 shttp.RequestInterface
	if rf, ok := ret.Get(0).(func(interface{}) shttp.RequestInterface); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shttp.RequestInterface)
		}
	}

	return r0
}

// Stream provides a mock function with given fields: body, contentLength
func (_m *RequestInterface) Stream(body io.Reader, contentLength int64) shttp.RequestInterface {
	ret := _m.Called(body, contentLength)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 shttp.RequestInterface
	if rf, ok := ret.Get(0).(func(io.Reader, int64) shttp.RequestInterface); ok {
		r0 = rf(body, contentLength)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shttp.RequestInterface)
		}
	}

	return r0
}

// URL provides a mock function with given fields: url
func (_m *RequestInterface) URL(url string) shttp.RequestInterface {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for URL")
	}

	var r0 shttp.RequestInterface
	if rf, ok := ret.Get(0).(func(string) shttp.RequestInterface); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shttp.RequestInterface)
		}
	}

	return r0
}

// WithExponentialBackoff provides a mock function with given fields: maxDelay, maxRetries
func (_m *RequestInterface) WithExponentialBackoff(maxDelay time.Duration, maxRetries int) shttp.RequestInterface {
	ret := _m.Called(maxDelay, maxRetries)

	if len(ret) == 0 {
		panic("no return value specified for WithExponentialBackoff")
	}

	var r0 shttp.RequestInterface
	if rf, ok := ret.Get(0).(func(time.Duration, int) shttp.RequestInterface); ok {
		r0 = rf(maxDelay, maxRetries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shttp.RequestInterface)
		}
	}

	return r0
}

// WithTimeout provides a mock function with given fields: duration
func (_m *RequestInterface) WithTimeout(duration time.Duration) shttp.RequestInterface {
	ret := _m.Called(duration)

	if len(ret) == 0 {
		panic("no return value specified for WithTimeout")
	}

	var r0 shttp.RequestInterface
	if rf, ok := ret.Get(0).(func(time.Duration) shttp.RequestInterface); ok {
		r0 = rf(duration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shttp.RequestInterface)
		}
	}

	return r0
}

// NewRequestInterface creates a new instance of RequestInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestInterface {
	mock := &RequestInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
