// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	integrations "github.com/stormkit-io/stormkit-io/src/lib/integrations"
	mock "github.com/stretchr/testify/mock"

	runner "github.com/stormkit-io/stormkit-io/src/ce/runner"
)

// RunnerUploaderInterface is an autogenerated mock type for the RunnerUploaderInterface type
type RunnerUploaderInterface struct {
	mock.Mock
}

// Upload provides a mock function with given fields: _a0
func (_m *RunnerUploaderInterface) Upload(_a0 runner.UploadArgs) (*integrations.UploadResult, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *integrations.UploadResult
	var r1 error
	if rf, ok := ret.Get(0).(func(runner.UploadArgs) (*integrations.UploadResult, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(runner.UploadArgs) *integrations.UploadResult); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*integrations.UploadResult)
		}
	}

	if rf, ok := ret.Get(1).(func(runner.UploadArgs) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRunnerUploaderInterface creates a new instance of RunnerUploaderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunnerUploaderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RunnerUploaderInterface {
	mock := &RunnerUploaderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
