// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	shttp "github.com/stormkit-io/stormkit-io/src/lib/shttp"
	mock "github.com/stretchr/testify/mock"
)

// ServiceFunc is an autogenerated mock type for the ServiceFunc type
type ServiceFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: r
func (_m *ServiceFunc) Execute(r *shttp.Router) *shttp.Service {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *shttp.Service
	if rf, ok := ret.Get(0).(func(*shttp.Router) *shttp.Service); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shttp.Service)
		}
	}

	return r0
}

// NewServiceFunc creates a new instance of ServiceFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceFunc {
	mock := &ServiceFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
