// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	asynq "github.com/hibiken/asynq"
	mock "github.com/stretchr/testify/mock"
)

// TaskClient is an autogenerated mock type for the TaskClient type
type TaskClient struct {
	mock.Mock
}

// Enqueue provides a mock function with given fields: task, opts
func (_m *TaskClient) Enqueue(task *asynq.Task, opts ...asynq.Option) (*asynq.TaskInfo, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, task)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 *asynq.TaskInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(*asynq.Task, ...asynq.Option) (*asynq.TaskInfo, error)); ok {
		return rf(task, opts...)
	}
	if rf, ok := ret.Get(0).(func(*asynq.Task, ...asynq.Option) *asynq.TaskInfo); ok {
		r0 = rf(task, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*asynq.TaskInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(*asynq.Task, ...asynq.Option) error); ok {
		r1 = rf(task, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskClient creates a new instance of TaskClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskClient {
	mock := &TaskClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
