// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	integrations "github.com/stormkit-io/stormkit-io/src/lib/integrations"
	mock "github.com/stretchr/testify/mock"
)

// uploadFunc is an autogenerated mock type for the uploadFunc type
type uploadFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *uploadFunc) Execute(_a0 integrations.File, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(integrations.File, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newUploadFunc creates a new instance of uploadFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newUploadFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *uploadFunc {
	mock := &uploadFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
